repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version of Black
    hooks:
      - id: black
        args: ["--line-length=79"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest stable version of Flake8
    hooks:
      - id: flake8
        additional_dependencies: 
          - flake8-docstrings
          - flake8-bugbear
        args: ["--max-line-length=79", "--ignore=E501"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0  # Use the latest stable version of isort
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
